/*
 * This file is generated by jOOQ.
 */
package com.example.webapi.infrastructure.jooq;


import com.example.webapi.infrastructure.jooq.tables.Memo;
import com.example.webapi.infrastructure.jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Demo3Db extends SchemaImpl {

    private static final long serialVersionUID = -161466271;

    /**
     * The reference instance of <code>demo3_db</code>
     */
    public static final Demo3Db DEMO3_DB = new Demo3Db();

    /**
     * The table <code>demo3_db.memo</code>.
     */
    public final Memo MEMO = com.example.webapi.infrastructure.jooq.tables.Memo.MEMO;

    /**
     * The table <code>demo3_db.user</code>.
     */
    public final User USER = com.example.webapi.infrastructure.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Demo3Db() {
        super("demo3_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Memo.MEMO,
            User.USER);
    }
}
