/*
 * This file is generated by jOOQ.
 */
package com.example.webapi.infrastructure.jooq;


import com.example.webapi.infrastructure.jooq.tables.Memo;
import com.example.webapi.infrastructure.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in demo3_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>demo3_db.memo</code>.
     */
    public static final Memo MEMO = Memo.MEMO;

    /**
     * The table <code>demo3_db.user</code>.
     */
    public static final User USER = User.USER;
}
